---
name: Build Images

on:
  schedule:
    - cron: "0 16 * * 6"
  workflow_dispatch:
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: kmpm/meshcentral

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: checout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # fetch all history for all tags

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: get information
        run: |
          echo "MC_VERSION=$( npm show meshcentral version)" >> $GITHUB_ENV
          echo "MC_TAG=$( git describe --tags --abbrev=0 --match img*)" >> $GITHUB_ENV

      - name: set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: login to github
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build regular images
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: ./builds/regular
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.MC_VERSION }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.MC_VERSION }}-${{ env.MC_TAG}}




        # run: |
        #   docker buildx build --build-arg PREINSTALL_LIBS=false --push \
        #     --tag ghcr.io/typhonragewind/meshcentral:latest \
        #     --tag ghcr.io/typhonragewind/meshcentral:$(npm show meshcentral version) \
        #     --platform linux/amd64,linux/arm/v7,linux/arm64 ./builds/regular/
